name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Deploy to VPS
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          TARGET: ${{ vars.TARGET_FOLDER }}
          USER: ${{ vars.DEPLOY_HOST_USERNAME }}
          ARGS: -avz --progress --delete --exclude=config.json --exclude=data/**

      - name: Run pm2 reload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: bro
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            NODE_ENV=production pm2 restart valobot --update-env
